// <auto-generated />
using System;
using AgiliRHFerias.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgiliRHFerias.WebAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.AvisoFerias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdEscalaFerias")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPagamentoFerias")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdEscalaFerias");

                    b.HasIndex("UserId");

                    b.ToTable("AvisosFerias");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CBO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InicioVigencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("NivelCargo")
                        .HasColumnType("int");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataDesligamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("ExerceLideranca")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdCargo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdConfigPeriodoAquisitivo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTurnoTrabalho")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("NumeroDependentes")
                        .HasColumnType("int");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdConfigPeriodoAquisitivo");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdTurnoTrabalho");

                    b.HasIndex("UserId");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Address = "583 Wall Dr. Gwynn Oak, MD 21207",
                            Country = "USA",
                            Name = "IT_Solutions Ltd"
                        },
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Address = "312 Forest Avenue, BF 923",
                            Country = "USA",
                            Name = "Admin_Solutions Ltd"
                        });
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.ConfigCalculoFerias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DividirFevereiroTrintaDias")
                        .HasColumnType("bit");

                    b.Property<bool>("DividirSempreNumeroDiasMes")
                        .HasColumnType("bit");

                    b.Property<bool>("DividirSempreTrintaDias")
                        .HasColumnType("bit");

                    b.Property<bool>("MultiplicarSempreNumeroDiasMes")
                        .HasColumnType("bit");

                    b.Property<bool>("MultiplicarSempreTrintaDias")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ConfigsCalculoFerias");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.ConfigINSS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ConfigsINSS");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.ConfigIRRF", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ValorDependentes")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ConfigsIRRF");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.ConfigOrcamentoFerias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ConfigsOrcamentoFerias");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.ConfigPeriodoAquisitivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InicioVigencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroDiasGozo")
                        .HasColumnType("int");

                    b.Property<int>("NumeroMesesTrabalhados")
                        .HasColumnType("int");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ConfigsPeriodoAquisitivo");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.ConfigReducaoDiasFerias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ConfigsReducaoDiasFerias");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeId");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            Age = 26,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Sam Raiden",
                            Position = "Software developer"
                        },
                        new
                        {
                            Id = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a"),
                            Age = 30,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Jana McLeaf",
                            Position = "Software developer"
                        },
                        new
                        {
                            Id = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            Age = 35,
                            CompanyId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Name = "Kane Miller",
                            Position = "Administrator"
                        });
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Filial")
                        .HasColumnType("bit");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.EscalaFerias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FimFerias")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdPeriodoAquisitivo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InicioFerias")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroDiasAbono")
                        .HasColumnType("int");

                    b.Property<int>("NumeroDiasDisponiveis")
                        .HasColumnType("int");

                    b.Property<int>("NumeroDiasGozo")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdPeriodoAquisitivo");

                    b.HasIndex("UserId");

                    b.ToTable("EscalasFerias");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.FaixaINSS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Aliquota")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("IdConfigINSS")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InicioVigencia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SalarioContribuicaoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioContribuicaoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdConfigINSS");

                    b.ToTable("FaixasINSS");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.FaixaIRRF", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Aliquota")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseCalculoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseCalculoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Deducao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("IdConfigIRRF")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InicioVigencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdConfigIRRF");

                    b.ToTable("FaixasIRRF");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.FaixaOrcamentoFerias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdConfigOrcamentoFerias")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InicioVigencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal>("Orcamento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdConfigOrcamentoFerias");

                    b.ToTable("FaixasOrcamentoFerias");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.FaixaReducaoDiasFerias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdConfigReducaoDiasFerias")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InicioVigencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroDiasFaltaFinal")
                        .HasColumnType("int");

                    b.Property<int>("NumeroDiasFaltaInicial")
                        .HasColumnType("int");

                    b.Property<int>("NumeroDiasFerias")
                        .HasColumnType("int");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdConfigReducaoDiasFerias");

                    b.ToTable("FaixasReducaoDiasFerias");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.FaixaTurnoTrabalho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Entrada1")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Entrada2")
                        .HasColumnType("time");

                    b.Property<Guid?>("IdTurnoTrabalho")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InicioVigencia")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PossuiIntervalo")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("Saida1")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Saida2")
                        .HasColumnType("time");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTurnoTrabalho");

                    b.ToTable("FaixasTurnoTrabalho");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.Falta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdColaborador")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Justificada")
                        .HasColumnType("bit");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdColaborador");

                    b.ToTable("Faltas");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.PeriodoAquisitivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdColaborador")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPeriodoConcessivo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdColaborador");

                    b.HasIndex("IdPeriodoConcessivo");

                    b.ToTable("PeriodosAquisitivos");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.PeriodoConcessivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdPeriodoAquisitivo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPeriodoAquisitivo");

                    b.ToTable("PeriodosConcessivos");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.TurnoTrabalho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TurnosTrabalho");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "93a81e96-0200-4766-9dae-88fc5b12aa8b",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "df6dd99a-e78e-45c7-a1db-2c88e2437cda",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "abfbf0f5-0562-45cb-a01a-c218037738c4",
                            Name = "Supervisor",
                            NormalizedName = "SUPERVISOR"
                        },
                        new
                        {
                            Id = "784bc4d8-c653-43bd-aab2-61f412747d2f",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.AvisoFerias", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.EscalaFerias", "EscalaFerias")
                        .WithMany()
                        .HasForeignKey("IdEscalaFerias")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgiliRHFerias.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EscalaFerias");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.Cargo", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.Colaborador", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgiliRHFerias.Entities.Models.ConfigPeriodoAquisitivo", "ConfigPeriodoAquisitivo")
                        .WithMany()
                        .HasForeignKey("IdConfigPeriodoAquisitivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgiliRHFerias.Entities.Models.Empresa", "Empresa")
                        .WithMany("Colaboradores")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgiliRHFerias.Entities.Models.TurnoTrabalho", "TurnoTrabalho")
                        .WithMany()
                        .HasForeignKey("IdTurnoTrabalho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgiliRHFerias.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("ConfigPeriodoAquisitivo");

                    b.Navigation("Empresa");

                    b.Navigation("TurnoTrabalho");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.ConfigCalculoFerias", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.ConfigINSS", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.ConfigIRRF", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.ConfigOrcamentoFerias", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.ConfigPeriodoAquisitivo", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.ConfigReducaoDiasFerias", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.Employee", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.Empresa", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.EscalaFerias", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.PeriodoAquisitivo", "PeriodoAquisitivo")
                        .WithMany("EscalasFerias")
                        .HasForeignKey("IdPeriodoAquisitivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgiliRHFerias.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodoAquisitivo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.FaixaINSS", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.ConfigINSS", "ConfigINSS")
                        .WithMany("FaixasINSS")
                        .HasForeignKey("IdConfigINSS");

                    b.Navigation("ConfigINSS");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.FaixaIRRF", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.ConfigIRRF", "ConfigIRRF")
                        .WithMany("FaixasIRRF")
                        .HasForeignKey("IdConfigIRRF");

                    b.Navigation("ConfigIRRF");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.FaixaOrcamentoFerias", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.ConfigOrcamentoFerias", "ConfigOrcamentoFerias")
                        .WithMany("FaixasOrcamentoFerias")
                        .HasForeignKey("IdConfigOrcamentoFerias");

                    b.Navigation("ConfigOrcamentoFerias");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.FaixaReducaoDiasFerias", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.ConfigReducaoDiasFerias", "ConfigReducaoDiasFerias")
                        .WithMany("FaixasReducaoDiasFerias")
                        .HasForeignKey("IdConfigReducaoDiasFerias");

                    b.Navigation("ConfigReducaoDiasFerias");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.FaixaTurnoTrabalho", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.TurnoTrabalho", "TurnoTrabalho")
                        .WithMany("FaixasTurnoTrabalho")
                        .HasForeignKey("IdTurnoTrabalho");

                    b.Navigation("TurnoTrabalho");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.Falta", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.Colaborador", "Colaborador")
                        .WithMany("Faltas")
                        .HasForeignKey("IdColaborador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.PeriodoAquisitivo", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.Colaborador", "Colaborador")
                        .WithMany("PeriodosAquisitivos")
                        .HasForeignKey("IdColaborador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgiliRHFerias.Entities.Models.PeriodoConcessivo", "PeriodoConcessivo")
                        .WithMany()
                        .HasForeignKey("IdPeriodoConcessivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("PeriodoConcessivo");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.PeriodoConcessivo", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.PeriodoAquisitivo", "PeriodoAquisitivo")
                        .WithMany()
                        .HasForeignKey("IdPeriodoAquisitivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodoAquisitivo");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.TurnoTrabalho", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgiliRHFerias.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AgiliRHFerias.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.Colaborador", b =>
                {
                    b.Navigation("Faltas");

                    b.Navigation("PeriodosAquisitivos");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.ConfigINSS", b =>
                {
                    b.Navigation("FaixasINSS");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.ConfigIRRF", b =>
                {
                    b.Navigation("FaixasIRRF");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.ConfigOrcamentoFerias", b =>
                {
                    b.Navigation("FaixasOrcamentoFerias");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.ConfigReducaoDiasFerias", b =>
                {
                    b.Navigation("FaixasReducaoDiasFerias");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.Empresa", b =>
                {
                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.PeriodoAquisitivo", b =>
                {
                    b.Navigation("EscalasFerias");
                });

            modelBuilder.Entity("AgiliRHFerias.Entities.Models.TurnoTrabalho", b =>
                {
                    b.Navigation("FaixasTurnoTrabalho");
                });
#pragma warning restore 612, 618
        }
    }
}
